# Generated by Django 5.2.6 on 2025-10-28 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_videojuegos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='foto_empleado',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_empleados/'),
        ),
    ]
